Simplify the pipelining of test stdout/err
Stop using explicit pipes and the "downtmp-shared-fifo" capability. This
provides live output for all runners, including qemu.

LP: #1320194

diff --git a/adt-run b/adt-run
--- a/adt-run
+++ b/adt-run
@@ -1362,112 +1362,42 @@ class Test:
         se = TempTestbedPath(testbed, self.what + '-stderr', autoclean=False)
 
         tb_test_path = os.path.join(tree.tb, self.path)
-        xenv = []
 
-        rc = testbed.execute('testchmod-' + self.what, ['chmod', '+x', '--', tb_test_path])
-        if rc:
-            bomb('failed to chmod +x %s' % tb_test_path)
-
-        # set up temporary dirs and build tree
-        test_adttmp = '/tmp/%s-adttmp' % self.what
+        # create script to run test
         test_artifacts = '%s/%s-artifacts' % (testbed.scratch, self.what)
-        xenv.append('ADTTMP=%s' % test_adttmp)
-        xenv.append('ADT_ARTIFACTS=%s' % test_artifacts)
+        script = '''set -e
+                    buildtree="%(t)s"
+                    rm -rf "%(a)s"; mkdir -m 1777 -- "%(a)s"
+                    export ADT_ARTIFACTS="%(a)s"
+                    export ADTTMP=$(mktemp -d --tmpdir adttmp.XXXXXX)
+                    trap "rm -rf $ADTTMP" EXIT INT QUIT PIPE
+                    cd "$buildtree"
+                    ''' % {'t': tree.tb, 'a': test_artifacts}
 
-        script = 'buildtree="$1"; shift\n'
-        script += 'rm -rf -- "$@"; mkdir -m 1777 -- "$@"\n'
+        if opts.user and 'rw-build-tree' in self.restriction_names:
+            script += 'chown -R %s "$buildtree\n' % opts.user
+
+        script += '''chmod +x %(t)s
+                     touch %(o)s %(e)s
+                     %(t)s 2> >(tee %(e)s >&2) > >(tee %(o)s)
+                  ''' % {'t': tb_test_path, 'o': so.tb, 'e': se.tb}
 
         if 'needs-root' not in self.restriction_names and opts.user is not None:
             if 'root-on-testbed' not in testbed.caps:
                 bomb('cannot change to user %s without root-on-testbed' % opts.user)
-            test_argv = ['su', '-s', '/bin/sh', opts.user, '-c', tb_test_path]
-            if opts.user:
-                if 'rw-build-tree' in self.restriction_names:
-                    script += ('chown -R %s "$buildtree" 2>/dev/null || chmod go+rwX "$buildtree"\n'
-                               % opts.user)
+            test_argv = ['su', '-s', '/bin/bash', opts.user, '-c', script]
         else:
-            test_argv = [tb_test_path]
+            test_argv = ['bash', '-c', script]
 
-        rc = testbed.execute('mktmpdir-' + self.what,
-                             ['sh', '-ec', script, 'x', tree.tb,
-                              test_adttmp, test_artifacts
-                              ])
-        if rc:
-            bomb("could not create test tmp dirs, exit code %d" % rc)
+        # run test script
+        self._debug('[-----------------------', True)
+        rc = testbed.execute_raw('test-' + self.what, test_argv, kind='test')
+        self._debug('-----------------------]', True)
+        debug('testbed executing test finished with exit status %i' % rc, 1)
 
-        # If we have a shared downtmp and can create a FIFO in it,
-        # route stdout/stderr through a common FIFO to watch them in realtime.
-        # Note that we can't use the coreutils tee with pipes, as it aborts on
-        # the first read error.
-        show_realtime = False
-        if shared_downtmp and 'downtmp-shared-fifo' in testbed.caps:
-            fifo_out = TempTestbedPath(testbed, 'test_stdout')
-            fifo_err = TempTestbedPath(testbed, 'test_stderr')
-            os.mkfifo(fifo_out.host)
-            os.mkfifo(fifo_err.host)
-            show_realtime = True
-            debug('shared downtmp with FIFO supported, showing test output in realtime', 1)
-        else:
-            debug('shared_downtmp with FIFO not supported', 1)
-
-        if show_realtime:
-            self._debug('[-----------------------', True)
-            debug('teeing to stdout: %s, stderr: %s' % (fifo_out.host, fifo_err.host), 2)
-            tee_out = os.fork()
-            if tee_out == 0:
-                fd_in = os.open(fifo_out.host, os.O_RDONLY)
-                fd_out = os.open(so.host, os.O_CREAT | os.O_WRONLY)
-
-                while True:
-                    block = os.read(fd_in, 1024)
-                    if not block:
-                        break
-                    os.write(fd_out, block)
-                    os.write(1, block)
-                os._exit(0)
-
-            tee_err = os.fork()
-            if tee_err == 0:
-                fd_in = os.open(fifo_err.host, os.O_RDONLY)
-                fd_out = os.open(se.host, os.O_CREAT | os.O_WRONLY)
-
-                while True:
-                    block = os.read(fd_in, 1024)
-                    if not block:
-                        break
-                    os.write(fd_out, block)
-                    os.write(2, block)
-                os._exit(0)
-
-            try:
-                rc = testbed.execute('test-' + self.what, test_argv,
-                                     so=fifo_out.tb, se=fifo_err.tb,
-                                     cwd=tree.tb,
-                                     xenv=xenv, kind='test')
-                debug('testbed executing test finished with exit status %i' % rc, 1)
-            finally:
-                # give tee childs another second to mop up last output
-                time.sleep(1)
-                os.kill(tee_out, signal.SIGTERM)
-                os.kill(tee_err, signal.SIGTERM)
-                os.waitpid(tee_out, 0)
-                os.waitpid(tee_err, 0)
-            self._debug('-----------------------]', True)
-
-        # without a shared downtmp we cannot show realtime output and need
-        # to show stdout afterwards
-        else:
-            self._debug('running...', True)
-            rc = testbed.execute('test-' + self.what, test_argv,
-                                 so=so.tb, se=se.tb, cwd=tree.tb,
-                                 xenv=xenv, kind='test')
-            self._debug('finished', True)
-            debug('testbed executing test finished with exit status %i' % rc, 1)
-
-            # copy stdout/err files to host
-            so.copyup()
-            se.copyup()
-
+        # copy stdout/err files to host
+        so.copyup()
+        se.copyup()
         se_size = os.path.getsize(se.host)
 
         # avoid mixing up stdout (from report) and stderr (from _debug) in output
@@ -1493,16 +1423,11 @@ class Test:
         sys.stderr.flush()
         time.sleep(0.1)
 
-        if os.path.getsize(so.host) != 0:
-            if not show_realtime:
-                self._debug(' - - - - - - - - - - stdout - - - - - - - - - -')
-                log_file(so.host)
-        else:
+        if os.path.getsize(so.host) == 0:
             # don't produce empty -stdout files in --output-dir
             os.unlink(so.host)
 
-        if se_size != 0:
-            if not show_realtime or 'allow-stderr' not in self.restriction_names:
+        if se_size != 0 and 'allow-stderr' not in self.restriction_names:
                 self._debug(' - - - - - - - - - - stderr - - - - - - - - - -')
                 log_file(se.host)
         else:
@@ -1519,9 +1444,9 @@ class Test:
             if not os.listdir(ap.host):
                 os.rmdir(ap.host)
 
-        # clean up temporary dirs
-        testbed.execute('cleanup-tmp-' + self.what,
-                        ['rm', '-rf', test_adttmp, test_artifacts])
+        # clean up artifacts dirs
+        testbed.execute('cleanup-artifacts-' + self.what,
+                        ['rm', '-rf', test_artifacts])
 
         if opts.shell or (opts.shell_fail and not passed):
             testbed.run_shell(tree.tb)
