tools/adt-setup-vm: Add setup steps that adt-buildvm-ubuntu-cloud does
So that vmdebootstrap generated VMs are functionally on par with the Ubuntu
cloud images: Set up serial console, dpkg unsafe-io, install some additional
packages, remove unnecessary packages, bump vmalloc on i386.

diff --git a/adt-setup-vm b/adt-setup-vm
--- a/adt-setup-vm
+++ b/adt-setup-vm
@@ -4,22 +4,28 @@
 #
 # autopkgtest is Copyright (C) 2006-2014 Canonical Ltd.
 #
-# Setup script for e. g. vmdebootstrap to start a root serial console on ttyS1,
-# set up networking for eth0, and enable deb-src apt sources. See
-# adt-virt-qemu(1) for details.
+# Setup script for e. g. vmdebootstrap or generic Debian/Ubuntu VM images to
+# start a root serial console on ttyS1, set up networking for eth0, configure
+# apt sources, install/clean up packages, etc.
+# See adt-virt-qemu(1) for details.
 #
 # You can set $ADT_APT_PROXY; if set, it will be configured in apt in
 # /etc/apt/apt.conf.d/01proxy. If apt-cacher-ng is running on localhost, this
 # will be used automatically, unless $ADT_APT_PROXY is set.
 
-set -e
+set -eu
 
-[ -d "$1" ] || {
-    echo "ERROR: This needs to be called with the root directory as argument" >&2
-    exit 1
-}
+if [ "${1:-}" = "--help" ]; then
+    echo "Usage: $0 [chroot dir]"
+    echo "if chroot dir is not given, run on the main system (for running in VMs)"
+    exit 0
+fi
 
-cat <<EOF > "$1/etc/init.d/autopkgtest"
+root=${1:-/}
+
+# set up init script for root shell on ttyS1; necessary for adt-virt-qemu local
+# images
+cat <<EOF > "$root/etc/init.d/autopkgtest"
 ### BEGIN INIT INFO
 # Provides:          autopkgtest
 # Required-Start:    mountkernfs \$local_fs
@@ -35,19 +41,42 @@ if [ "\$1" = start ]; then
 fi
 EOF
 
-chmod 755 "$1/etc/init.d/autopkgtest"
-chroot "$1" update-rc.d autopkgtest defaults
+chmod 755 "$root/etc/init.d/autopkgtest"
+chroot "$root" update-rc.d autopkgtest defaults
 
-# enable deb-src apt sources
-sed -i '/^deb / s/deb \(.*\)$/deb \1\ndeb-src \1/' "$1/etc/apt/sources.list"
+# set up serial console on upstart systems
+if [ -e "$root/etc/init/tty2.conf" -a ! -e "$root/etc/init/ttyS0.conf" ]; then
+    sed 's/tty2/ttyS0/g; s! *exec.*$!exec /sbin/getty -L ttyS0 115200 vt102!' \
+        "$root/etc/init/tty2.conf" > "$root/etc/init/ttyS0.conf"
+fi
+
+# set up apt sources
+mirror_rel=`awk '/^deb .*(debian|ubuntu)/ { print $2,$3; exit }' "$root/etc/apt/sources.list"`
+if [ "${mirror_rel%ubuntu*}" != "$mirror_rel" ]; then
+    cat << EOF > "$root/etc/apt/sources.list"
+deb     $mirror_rel main restricted universe multiverse
+deb     ${mirror_rel}-updates main restricted universe multiverse
+deb-src $mirror_rel main restricted universe multiverse
+deb-src ${mirror_rel}-updates main restricted universe multiverse
+EOF
+else
+    cat << EOF > "$root/etc/apt/sources.list"
+deb $mirror_rel main contrib non-free
+deb-src $mirror_rel main contrib non-free
+EOF
+fi
 
 # set up networking
-/bin/echo -e '\nauto eth0\niface eth0 inet dhcp' >> "$1"/etc/network/interfaces
+if ! grep -qr eth0 /etc/network/interfaces /etc/network/interfaces.d/; then
+    /bin/echo -e '\nauto eth0\niface eth0 inet dhcp' >> "$root"/etc/network/interfaces
+fi
 
-echo "Acquire::Languages \"none\";" > "$1"/etc/apt/apt.conf.d/90nolanguages
+# go-faster apt/dpkg
+echo "Acquire::Languages \"none\";" > "$root"/etc/apt/apt.conf.d/90nolanguages
+echo 'force-unsafe-io' > /etc/dpkg/dpkg.cfg.d/autopkgtest
 
 # auto-detect apt-cacher-ng
-if [ -z "$ADT_APT_PROXY" ]; then
+if [ -z "${ADT_APT_PROXY:-}" ]; then
     RES=`apt-config shell proxy Acquire::http::Proxy`
     eval $RES
     if echo "$proxy" | egrep -q '(localhost|127\.0\.0\.[0-9]*):3142'; then
@@ -57,10 +86,35 @@ if [ -z "$ADT_APT_PROXY" ]; then
     fi
 fi
 
-chroot "$1" apt-get update
+# upgrade, install some necessary packages
+chroot "$root" apt-get update
+[ "${ADT_SETUP_VM_UPGRADE:-}" = false ] || chroot "$root" apt-get -y dist-upgrade
+
+if [ "${mirror_rel%ubuntu*}" != "$mirror_rel" ]; then
+    # provides kmods like scsi_debug or mac80211_hwsim
+    chroot "$root" apt-get install -y linux-generic
+fi
+# some tests use a lot of /dev/random, avoid hangs
+chroot "$root" apt-get install -y haveged
+
+# clean up some unnecessary packages
+for p in accountsservice apt-xapian-index cryptsetup landscape-client \
+    landscape-common open-vm-tools w3m vim-runtime aptitude-common \
+    command-not-found-data man-db manpages ntfs-3g sosreport \
+    ubuntu-release-upgrader-core; do
+    chroot "$root" apt-get --auto-remove -y purge $p || true
+done
+chroot "$root" apt-get clean
 
 # set up apt proxy, if given (this might be an IP which only works in the VM,
-# so don't run the previous apt-get update with that already)
-if [ -n "$ADT_APT_PROXY" ]; then
-    echo "Acquire::http { Proxy \"$ADT_APT_PROXY\"; };" > "$1"/etc/apt/apt.conf.d/01proxy
+# so don't run the previous apt-get with that already)
+if [ -n "${ADT_APT_PROXY:-}" ]; then
+    echo "Acquire::http { Proxy \"$ADT_APT_PROXY\"; };" > "$root"/etc/apt/apt.conf.d/01proxy
+fi
+
+# bump vmalloc on i386, necessary for tests like udisks2
+if [ "$(chroot "$root" dpkg --print-architecture)" = "i386" ]; then
+    echo 'GRUB_CMDLINE_LINUX_DEFAULT="console=ttyS0 vmalloc=512M"' > \
+        "$root/etc/default/grub.d/90-adt-vmalloc.cfg"
+    chroot "$root" update-grub
 fi
